export const config = {
   NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
   SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
   // cloud config
   CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
   UPLOAD_PRESET: process.env.NEXT_PUBLIC_UPLOAD_PRESET,
   CLOUDINARY_API_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY,
   CLOUDINARY_API_SECRET: process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET,
};
